name: build
on: 
  workflow_dispatch:
  push:
  
env:
  workernumber: 3
  
jobs:
  nmatrix:
    runs-on: ubuntu-latest
    outputs:
      nmatrix: ${{ steps.set-nmatrix.outputs.Nmatrix }}
      
    steps:
      - id: set-nmatrix
        run: |
          #criar matrix para workernumber
          for (( x=1; x<="$workernumber"; x++ )); do  
              xx=$["$workernumber" - "$x" + "1"]
              xxx="$xxx,'$xx'"
              xxxx=$(echo "$xxx" | sed 's/^,//')
          done
          echo "Nmatrix=[$xxxx]" >> $GITHUB_OUTPUT

  make:
    needs: nmatrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Nworks: ${{fromJSON(needs.nmatrix.outputs.nmatrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Make
        uses: gitbarnabedikartola/big-vs@main
        with:
          workernumber: $workernumber
          blenderversion: 3.3.1
          blenderfile: big-vs-ubuntu.blend
          #cena a ser renderizada, em branco renderiza a primeira cena
          scene: 03-montagem
          #preencher se quiser renderizar só uma parte, deixar em branco para renderizar os frames do .blend
          startframe: 0
          endframe: 99
        
      - name: push to git releases
        shell: bash
        run: |
          echo ${{ github.repository }}
          ls -lh
          echo ${{ secrets.TOKEN_UPLOAD }} | gh auth login --with-token
          # gh release create renders --title renders --repo ${{ github.repository }} --notes "sempre usados"
          for i in *.mkv; do
            gh release upload renders --repo ${{ github.repository }} --clobber $i
          done
      
      #   ##Tmate ##
      # - name: Setup TMATE Session
      #   uses: mxschmitt/action-tmate@v3    
